<a href="https://colab.research.google.com/github/princevalerie/TATA/blob/main/Data_Cleaning_Tata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
import pandas as pd
import numpy as np

In [24]:
df=pd.read_excel("/content/drive/MyDrive/tata/Online Retail Data Set.xlsx")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [26]:
df['UnitPrice']=df['UnitPrice'].astype(str).str.replace('-', '').astype(float)
df['UnitPrice']

0         2.55
1         3.39
2         2.75
3         3.39
4         3.39
          ...
541904    0.85
541905    2.10
541906    4.15
541907    4.15
541908    4.95
Name: UnitPrice, Length: 541909, dtype: float64

In [27]:
df['Revenue']=df['Quantity']*df['UnitPrice']

In [28]:
def fill_revenue(row):
    if row['Quantity'] <= 0 or row['UnitPrice'] <= 0:
        return None
    else:
        return row['Quantity'] * row['UnitPrice']


df['Revenue'] = df.apply(fill_revenue, axis=1)

In [29]:
df['Revenue']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
541904    10.20
541905    12.60
541906    16.60
541907    16.60
541908    14.85
Name: Revenue, Length: 541909, dtype: float64

In [30]:
def fill_revenue(row):
    if row['Quantity'] <= 0 or row['UnitPrice'] <= 0:
        return -1 * row['Quantity'] * row['UnitPrice']
    else:
        return None


df['Revenue Refund'] = df.apply(fill_revenue, axis=1)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   InvoiceNo       541909 non-null  object
 1   StockCode       541909 non-null  object
 2   Description     540455 non-null  object
 3   Quantity        541909 non-null  int64
 4   InvoiceDate     541909 non-null  datetime64[ns]
 5   UnitPrice       541909 non-null  float64
 6   CustomerID      406829 non-null  float64
 7   Country         541909 non-null  object
 8   Revenue         530106 non-null  float64
 9   Revenue Refund  11803 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 41.3+ MB

In [33]:
df = df[df['Description'].notna()]

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 540455 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   InvoiceNo       540455 non-null  object
 1   StockCode       540455 non-null  object
 2   Description     540455 non-null  object
 3   Quantity        540455 non-null  int64
 4   InvoiceDate     540455 non-null  datetime64[ns]
 5   UnitPrice       540455 non-null  float64
 6   CustomerID      406829 non-null  float64
 7   Country         540455 non-null  object
 8   Revenue         530106 non-null  float64
 9   Revenue Refund  10349 non-null   float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 45.4+ MB

In [35]:
df.describe()

,Quantity,UnitPrice,CustomerID,Revenue,Revenue Refund
count,540455.000000,540455.000000,406829.000000,530106.000000,10349.000000
mean,9.603129,4.705391,15287.690570,20.163531,86.656922
std,218.007598,96.885686,1713.600303,271.205627,1932.722230
min,-80995.000000,0.000000,12346.000000,0.001000,-0.000000
25%,1.000000,1.250000,13953.000000,3.750000,2.500000
50%,3.000000,2.080000,15152.000000,9.900000,7.500000
75%,10.000000,4.130000,16791.000000,17.700000,16.500000
max,80995.000000,38970.000000,18287.000000,168469.600000,168469.600000

In [ ]:
df.to_excel('Online Retail Dataset Done.xlsx', index=False)